apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellmeet-frontend-deployment
  labels:
    app: intellmeet-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intellmeet-frontend
  template:
    metadata:
      labels:
        app: intellmeet-frontend
    spec:
      containers:
      - name: frontend-ui
        image: krenilpatel05/intellmeet-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: intellmeet-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: intellmeet-frontend
  ports:
  - port: 80
    targetPort: 80